### ISSUE TITLE
::selection pour un peu plus de lisibilé des textes selectionné

### ISSUE THREAD

**Issue by ArnaudBan** [willybahuaud/2018#1]
Salut,
Je voulais faire une petite pull request pour ajouter ce petit bout de code dans le CSS mais je ne vois pas comment tu minifies ton CSS. 

```css
::selection{background:var(--primary);text-shadow:none;}
::-moz-selection{background:var(--primary);text-shadow:none;}
```
Si tu peux m'expliquer comment faire pour généré le fichier minifié, je te fait une pull request. 

Question visibilité ce changement donne ca pour moi : 

Avant
<img width="524" alt="capture d ecran 2017-12-05 a 21 06 09" src="https://user-images.githubusercontent.com/1626370/33628216-4fac4884-da00-11e7-802a-46911639f52a.png">

Aprés
<img width="528" alt="capture d ecran 2017-12-05 a 21 05 04" src="https://user-images.githubusercontent.com/1626370/33628202-44d7d11c-da00-11e7-9bec-f0a895409af7.png">

C'est un détail mais j'ai remarqué ça j'ai envie d'aider.
